name: Build Shad1k1 Desktop322
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Full Build and Export
        run: |
          # Создаем папку для готовых пакетов на РАБОЧЕЙ МАШИНЕ (не в докере)
          mkdir -p ./final_packages

          # Запускаем контейнер
          docker run --name builder --privileged gentoo/stage3:latest /bin/bash -c "
            emerge-webrsync &&
            emerge --quiet app-eselect/eselect-repository &&
            eselect repository enable guru &&
            emaint sync -r guru &&
            
            # Настройки (твои флаги и маска)
            echo 'COMMON_FLAGS=\"-O2 -pipe\"' > /etc/portage/make.conf &&
            echo 'CFLAGS=\"\${COMMON_FLAGS}\"' >> /etc/portage/make.conf &&
            echo 'CXXFLAGS=\"\${COMMON_FLAGS}\"' >> /etc/portage/make.conf &&
            echo 'MAKEOPTS=\"-j2\"' >> /etc/portage/make.conf &&
            echo 'BINPKG_FORMAT=\"xpak\"' >> /etc/portage/make.conf &&
            echo 'FEATURES=\"buildpkg\"' >> /etc/portage/make.conf &&
            echo 'ACCEPT_LICENSE=\"*\"' >> /etc/portage/make.conf &&
            
            mkdir -p /etc/portage/package.accept_keywords &&
            echo 'gui-wm/swayfx ~amd64' >> /etc/portage/package.accept_keywords/build &&
            echo 'gui-libs/wlroots ~amd64' >> /etc/portage/package.accept_keywords/build &&
            echo 'gui-apps/waybar ~amd64' >> /etc/portage/package.accept_keywords/build &&
            
            mkdir -p /etc/portage/package.use &&
            echo '*/* wayland' >> /etc/portage/package.use/build &&
            echo 'gui-apps/waybar tray network pulseaudio' >> /etc/portage/package.use/build &&
            echo 'gui-libs/wlroots x11-backend' >> /etc/portage/package.use/build &&
            
            # Сама сборка
            emerge --verbose gui-wm/swayfx gui-apps/waybar
          "
          
          # Копируем файлы, пока контейнер еще существует в системе (даже если он остановлен)
          docker cp builder:/var/cache/binpkgs/ ./final_packages/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gentoo-binaries-shad1k1
          path: ./final_packages/binpkgs/
          
